# Configuration for Smart Real Training System
trainer:
  population_size: 1000
  target_vram_percent: 0.85
  generations: 50
  difficulty_increase_interval: 5
  max_difficulty: 4
  elite_size: 100
  trading_cost: 0.0002
  stop_loss_pips: 30
  take_profit_pips: 60
  max_position_size: 0.1
  initial_balance: 100000.0  # Updated to $100,000
  data_file: "data/EURUSD_H1.csv"
  
# Model configuration
model:
  input_size: 26  # Updated to include technical indicators
  hidden_size: 512
  output_size: 3
  
# Reward system configuration
rewards:
  first_trade_bonus: 1000
  idle_penalty: -100
  idle_penalty_threshold: 1000
  holding_penalty: -1
  max_leverage: 100
